### ISSUE TITLE
(E173 u-1) Could not identify active port 

### ISSUE THREAD

**Issue by doushabu06** [mcphail/linux_huawei_unlocker#10]
Hi! I have Huawei E173 u-1 and it has refused to unlock.

Let my explain in brief:
I usualy use this modem by way of temporary unlocking because it's firmware is locked.
The software that I use to unlock it resides in my windows 7 os.
The software that I use on windows is called Huawei Modem Unlocker.exe.
Here is the link http://www.doncaprio.com/2012/11/how-to-flash-huawei-usb-modems-and-re-install-the-firmware.html.
When I unlock it, it will remain unlocked unless I unplug or shut down my pc
So I unlock it using windows 7 then I reboot and boot to ubuntu.
If I shut down my pc or unplug the modem it locks again. 
So I unlock it in windows then reboot to ubuntu and it works fine. 
Now the problem is that I cannot unlock it in ubuntu using linux_huawei_unlocker.

My system is
-Xbuntu 14.04.1 LTS
-Python 2.7.6
-Huawei E173 u-1
-Country: Kenya
- Original modem carrier is safaricom
- The carrier of the SIM you used in the unlock process: Orange Kenya
- It looks for ports for some time and then fails to find the active port
- Any suggestions: How about making a GUI like the one for Huawei Modem Unlocker.exe. 

Thanks alot by the way

**Comment by mcphail** [comment]
Hi. Thanks for the feedback.

I've realised I probably can't go any further with this project as I'd need a locked version of every Huawei modem in circulation to test and I don't have the time, money or resources to do that. I don't think there's much point making a GUI wrapper as the underlying code doesn't cope with today's modems.

When I get a chance I'll update the README to state that this code is for historic interest only. Sorry i can't be more helpful and thank you for taking the time to open the issue. I hope someone else can solve your problems. SIM-locking is evil!
